tap "acsandmann/tap", trusted: true
tap "anomalyco/tap", trusted: true
tap "asheshgoplani/tap", trusted: true
tap "charmbracelet/tap", trusted: true
tap "epk/epk", trusted: true
tap "hashicorp/tap", trusted: true
tap "lanes-sh/lanes", trusted: true
tap "manaflow-ai/cmux", trusted: true
tap "stripe/stripe-cli", trusted: true
tap "superset-sh/tap", trusted: true
brew "age"
brew "acsandmann/tap/rift"
brew "openssl@3"
brew "agent-browser"
brew "bat"
brew "cmake"
brew "diff-so-fancy"
brew "exiftool"
brew "eza"
brew "ffmpeg"
brew "fzf"
brew "gcalcli"
brew "gemini-cli"
brew "gh"
brew "git"
brew "gum"
brew "imagemagick"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "libsodium"
brew "libyaml"
brew "mise"
brew "mosh"
brew "mysql"
brew "neovim"
brew "openjdk"
brew "pandoc"
brew "reattach-to-user-namespace"
brew "redis"
brew "ripgrep"
brew "sops"
brew "sox"
brew "starship"
brew "stow"
brew "stylua"
brew "swiftlint"
brew "tmux"
brew "uv"
brew "vips"
brew "watch"
brew "worktrunk"
brew "xcbeautify"
brew "xcodegen"
brew "zoxide"
brew "zsh"
brew "anomalyco/tap/opencode"
brew "asheshgoplani/tap/agent-deck"
brew "charmbracelet/tap/crush"
brew "hashicorp/tap/terraform"
brew "stripe/stripe-cli/stripe"
brew "superset-sh/tap/superset"
cask "1password-cli"
cask "alacritty"
cask "basictex"
cask "cmux"
cask "codex"
cask "flashspace"
cask "epk/epk/font-sf-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "inkscape"
cask "iterm2"
cask "lanes-sh/lanes/lanes"
cask "ngrok"
cask "orbstack"
cask "stats"
