# Simple two-line prompt matching prompt.zsh style
format = """
╭─ $directory$git_branch$git_status
╰─ $character"""

[directory]
style = "fg:blue"
format = "[$path]($style)"
truncation_length = 0
truncate_to_repo = false

[status]
style = "fg:green"
success_symbol = ""
format = '[$symbol]($style) '
disabled = false

[character]
success_symbol = "[\\$](bold white)"
error_symbol = "[\\$](bold white)"

[git_branch]
format = '[[ $branch ](fg:green)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:purple)]($style)'
